name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    name: Build Resume 
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: resume.tex
      - name: Archive resume artifact
        uses: actions/upload-artifact@v2
        with:
          name: resume_${{ github.sha }}
          path: resume.pdf
  release:
    name: Create Release 
    runs-on: ubuntu-latest
    needs: build_latex
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Download resume pdf artifact
        uses: actions/download-artifact@v2
        with:
          name: resume_${{ github.sha }}
      - name: Upload release
        uses: ncipollo/release-action@v1
        with:
          artifacts: resume.pdf
          token: ${{ secrets.GITHUB_TOKEN }}

    
    