name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: resume.tex
      - name: push pdf to github.com/ko28/resume
        run: |
          # configure git
          git config --global user.name "Daniel Ko"
          git config --global user.email "ko28@wisc.edu"
          # push pdf file to this repo
          git add resume.pdf
          git commit -m "[github actions] update pdf"
          git push
      - name: push pdf to ko28.github.io
        run: |
          mkdir ~/.ssh
          chmod 700 ~/.ssh
          echo "$DEPLOY_KEY" > ~/.ssh/key 
          chmod 600 ~/.ssh/key
          git config --global core.sshCommand "ssh -i ~/.ssh/key -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no"
          git clone --depth=1 git@github.com:ko28/ko28.github.io.git "$GITHUB_WORKSPACE/website"
             
          cp -f resume.pdf "$GITHUB_WORKSPACE/website/assets/daniel_resume.pdf"
          cd "$GITHUB_WORKSPACE/website"
          git add assets/daniel_resume.pdf
          git commit -m "[github actions] compile-latex-demo, update pdf"
          git push
        env:
          DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
