name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: resume.tex
      - name: push pdf to github.com/ko28/resume
        run: |
          # configure git
          git config --global user.name "Daniel Ko"
          git config --global user.email "ko28@wisc.edu"
          # push pdf file to this repo
          git add resume.pdf
          git commit -m "[github actions] update pdf"
          git push
